sudo: required
services:
  - docker

before_install:
  - docker build -t zolingen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zolingen/react-test npm test -- --coverage

after_success:
  - docker build -t zolingen/multi-client ./client
  - docker build -t zolingen/multi-nginx ./nginx
  - docker build -t zolingen/multi-server ./server
  - docker build -t zolingen/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub -poging 5 voor upload plus mem
  - docker push zolingen/multi-client
  - docker push zolingen/multi-nginx
  - docker push zolingen/multi-server
  - docker push zolingen/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app : multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-643932763253
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY 